//! Differential parity test for the `color` package itself.
//!
//! `tests/testdata/color_golden.tsv` is generated by `tools/color_golden`,
//! which drives the *original* `github.com/fatih/color` across a matrix of
//!
//! ```text
//! attribute sets × operations × argument lists × global NoColor × local override
//! ```
//!
//! and records the exact bytes produced plus the `(n int, err error)` byte
//! counts. Regenerate with:
//!
//! ```sh
//! cd tools/color_golden && go run . > ../../tests/testdata/color_golden.tsv
//! ```
//!
//! This test replays every case against the Rust port and asserts byte-level
//! equality, which covers `wrap`/`format`/`unformat`, the per-attribute reset
//! table, `NoColor` precedence, the `Sprint`/`Sprintln` spacing rules, the
//! helper functions and `Equals`.

use std::sync::{Mutex, MutexGuard, OnceLock};

use color::{Attribute, Color, SharedBuffer, Value};

fn test_lock() -> &'static Mutex<()> {
    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(()))
}

fn serial() -> MutexGuard<'static, ()> {
    test_lock().lock().unwrap_or_else(|e| e.into_inner())
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
        .collect()
}

fn unhex_str(s: &str) -> String {
    String::from_utf8(unhex(s)).expect("valid utf-8")
}

fn parse_attrs(spec: &str) -> Vec<Attribute> {
    if spec.is_empty() {
        return Vec::new();
    }
    spec.split(',')
        .map(|v| Attribute(v.parse().expect("attribute")))
        .collect()
}

/// Decodes the self-describing "argspec" produced by the Go generators.
///
/// Every tag `tools/color_golden` and `tools/fuzz_parity` can emit is handled,
/// so the randomized corpus replays through `COLOR_GOLDEN` unchanged.
fn parse_args(spec: &str) -> Vec<Value> {
    if spec.is_empty() {
        return Vec::new();
    }
    spec.split(';').map(parse_arg).collect()
}

fn parse_arg(spec: &str) -> Value {
    if spec == "n" {
        return Value::Nil;
    }
    let (tag, body) = spec.split_once(':').unwrap_or((spec, ""));
    match tag {
        "b" => Value::Bool(body == "1"),
        "i" => Value::Int(body.parse().expect("int")),
        "u" => Value::Uint(body.parse().expect("uint")),
        "f" => Value::Float(f64::from_bits(
            u64::from_str_radix(body, 16).expect("float bits"),
        )),
        "s" => Value::Str(unhex_str(body)),
        "r" => Value::Rune(
            char::from_u32(body.parse::<i64>().expect("rune") as u32).expect("valid rune"),
        ),
        "y" => Value::Bytes(unhex(body)),
        "e" => Value::Error(unhex_str(body)),
        "l" => Value::Slice(parse_args(&unhex_str(body))),
        other => panic!("unknown argspec tag {other:?}"),
    }
}

/// Applies the local `DisableColor`/`EnableColor` override encoded in the
/// golden record.
fn new_color(attrs: &[Attribute], override_kind: u8) -> Color {
    let mut c = Color::new(attrs);
    match override_kind {
        1 => c.disable_color(),
        2 => c.enable_color(),
        _ => {}
    }
    c
}

type HelperFn = fn(&str, &[Value]) -> String;

fn string_helper(name: &str) -> HelperFn {
    match name {
        "BlackString" => color::black_string,
        "RedString" => color::red_string,
        "GreenString" => color::green_string,
        "YellowString" => color::yellow_string,
        "BlueString" => color::blue_string,
        "MagentaString" => color::magenta_string,
        "CyanString" => color::cyan_string,
        "WhiteString" => color::white_string,
        "HiBlackString" => color::hi_black_string,
        "HiRedString" => color::hi_red_string,
        "HiGreenString" => color::hi_green_string,
        "HiYellowString" => color::hi_yellow_string,
        "HiBlueString" => color::hi_blue_string,
        "HiMagentaString" => color::hi_magenta_string,
        "HiCyanString" => color::hi_cyan_string,
        "HiWhiteString" => color::hi_white_string,
        other => panic!("unknown helper {other:?}"),
    }
}

type PrintHelperFn = fn(&str, &[Value]);

fn print_helper(name: &str) -> PrintHelperFn {
    match name {
        "Black" => color::black,
        "Red" => color::red,
        "Green" => color::green,
        "Yellow" => color::yellow,
        "Blue" => color::blue,
        "Magenta" => color::magenta,
        "Cyan" => color::cyan,
        "White" => color::white,
        "HiBlack" => color::hi_black,
        "HiRed" => color::hi_red,
        "HiGreen" => color::hi_green,
        "HiYellow" => color::hi_yellow,
        "HiBlue" => color::hi_blue,
        "HiMagenta" => color::hi_magenta,
        "HiCyan" => color::hi_cyan,
        "HiWhite" => color::hi_white,
        other => panic!("unknown print helper {other:?}"),
    }
}

/// Runs one golden record, returning the produced bytes and reported count.
fn run_case(
    attrs: &[Attribute],
    op: &str,
    format: &str,
    args: &[Value],
    override_kind: u8,
) -> (Vec<u8>, i64) {
    // Helper functions with their own dispatch.
    if let Some(name) = op.strip_prefix("helper:") {
        return (string_helper(name)(format, args).into_bytes(), -1);
    }
    if let Some(name) = op.strip_prefix("printhelper:") {
        let buf = SharedBuffer::new();
        color::set_output(buf.writer());
        print_helper(name)(format, args);
        return (buf.bytes(), -1);
    }
    if op == "equals" {
        // `format` carries the second attribute set.
        let other = parse_attrs(format);
        let eq = Color::new(attrs).equals(&Color::new(&other));
        return (format!("{eq}").into_bytes(), -1);
    }

    match op {
        "sprint" => (
            new_color(attrs, override_kind).sprint(args).into_bytes(),
            -1,
        ),
        "sprintln" => (
            new_color(attrs, override_kind).sprintln(args).into_bytes(),
            -1,
        ),
        "sprintfunc" => (
            new_color(attrs, override_kind).sprint_func()(args).into_bytes(),
            -1,
        ),
        "sprintlnfunc" => (
            new_color(attrs, override_kind).sprintln_func()(args).into_bytes(),
            -1,
        ),
        "sprintf" => (
            new_color(attrs, override_kind)
                .sprintf(format, args)
                .into_bytes(),
            -1,
        ),
        "fprint" => {
            let buf = SharedBuffer::new();
            let n = new_color(attrs, override_kind)
                .fprint(&mut buf.clone(), args)
                .expect("fprint");
            (buf.bytes(), n as i64)
        }
        "fprintln" => {
            let buf = SharedBuffer::new();
            let n = new_color(attrs, override_kind)
                .fprintln(&mut buf.clone(), args)
                .expect("fprintln");
            (buf.bytes(), n as i64)
        }
        "fprintf" => {
            let buf = SharedBuffer::new();
            let n = new_color(attrs, override_kind)
                .fprintf(&mut buf.clone(), format, args)
                .expect("fprintf");
            (buf.bytes(), n as i64)
        }
        "print" => {
            let buf = SharedBuffer::new();
            color::set_output(buf.writer());
            let n = new_color(attrs, override_kind).print(args).expect("print");
            (buf.bytes(), n as i64)
        }
        "println" => {
            let buf = SharedBuffer::new();
            color::set_output(buf.writer());
            let n = new_color(attrs, override_kind)
                .println(args)
                .expect("println");
            (buf.bytes(), n as i64)
        }
        "printf" => {
            let buf = SharedBuffer::new();
            color::set_output(buf.writer());
            let n = new_color(attrs, override_kind)
                .printf(format, args)
                .expect("printf");
            (buf.bytes(), n as i64)
        }
        "setwriter" => {
            let buf = SharedBuffer::new();
            let mut w = buf.clone();
            let c = new_color(attrs, override_kind);
            c.set_writer(&mut w);
            use std::io::Write;
            w.write_all(b"X").unwrap();
            c.unset_writer(&mut w);
            (buf.bytes(), -1)
        }
        "setunset" => {
            let buf = SharedBuffer::new();
            color::set_output(buf.writer());
            let c = new_color(attrs, override_kind);
            c.set();
            let mut w = buf.clone();
            use std::io::Write;
            w.write_all(b"X").unwrap();
            color::unset();
            (buf.bytes(), -1)
        }
        other => panic!("unknown op {other:?}"),
    }
}

#[test]
fn matches_go_color_byte_for_byte() {
    let _g = serial();

    // `COLOR_GOLDEN` lets the randomized fuzz harness point this replay at a
    // freshly generated corpus.
    let path = std::env::var("COLOR_GOLDEN").unwrap_or_else(|_| {
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/testdata/color_golden.tsv"
        )
        .to_string()
    });
    let golden =
        std::fs::read_to_string(&path).expect("golden file; regenerate with tools/color_golden");

    let mut total = 0usize;
    let mut failed = 0usize;
    let mut examples: Vec<String> = Vec::new();

    for (lineno, line) in golden.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        assert_eq!(f.len(), 8, "malformed golden record on line {}", lineno + 1);

        let attrs = parse_attrs(f[0]);
        let op = f[1];
        let format_raw = f[2];
        let argspec = f[3];
        let global_no_color: bool = f[4].parse().expect("bool");
        let override_kind: u8 = f[5].parse().expect("override");
        let want = unhex(f[6]);
        let want_n: i64 = f[7].parse().expect("n");

        // `equals` smuggles the second attribute set through the format column
        // (hex-encoded like every other format string).
        let format = unhex_str(format_raw);
        let args = parse_args(argspec);

        color::set_no_color(global_no_color);
        let (got, got_n) = run_case(&attrs, op, &format, &args, override_kind);

        total += 1;
        if got != want || got_n != want_n {
            failed += 1;
            if examples.len() < 25 {
                examples.push(format!(
                    "line {}: op={op} attrs=[{}] format={:?} args={argspec} nocolor={global_no_color} override={override_kind}\n     want: {:?} (n={want_n})\n      got: {:?} (n={got_n})",
                    lineno + 1,
                    f[0],
                    format,
                    String::from_utf8_lossy(&want),
                    String::from_utf8_lossy(&got),
                ));
            }
        }
    }

    // Leave the globals in a sane state for any test that follows.
    color::set_no_color(false);
    color::set_output(color::std_out());

    assert!(
        failed == 0,
        "{failed} of {total} color parity cases failed:\n\n{}",
        examples.join("\n\n")
    );

    eprintln!("verified {total} color parity cases against real Go output");
}
