//! Differential parity test for the Go `fmt` engine.
//!
//! `tests/testdata/gofmt_golden.tsv` is generated by `color-parity-oracle/gofmt_golden`,
//! which evaluates a large matrix of format strings against representative
//! argument lists using the *real* Go `fmt` package:
//!
//! ```sh
//! cd ../color-parity-oracle/gofmt_golden && go run . > ../../color/tests/testdata/gofmt_golden.tsv
//! ```
//!
//! This test replays every one of those cases through [`color::gofmt`] and
//! asserts the output is byte-identical to Go's.

use color::{gofmt, Value};

/// Number of records `color-parity-oracle/gofmt_golden` writes into the committed corpus.
///
/// Without this the test passes vacuously against a truncated or empty golden
/// file — it would report "0 of 0 cases failed" and be green having compared
/// nothing.
const COMMITTED_CASES: usize = 148_500;

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
        .collect()
}

fn unhex_str(s: &str) -> String {
    String::from_utf8(unhex(s)).expect("valid utf-8")
}

/// Decodes the self-describing "argspec" produced by the Go generator.
fn parse_args(spec: &str) -> Vec<Value> {
    if spec.is_empty() {
        return Vec::new();
    }
    spec.split(';').map(parse_arg).collect()
}

fn parse_arg(spec: &str) -> Value {
    if spec == "n" {
        return Value::Nil;
    }
    let (tag, body) = spec.split_once(':').unwrap_or((spec, ""));
    match tag {
        "b" => Value::Bool(body == "1"),
        "i" => Value::Int(body.parse().expect("int")),
        "u" => Value::Uint(body.parse().expect("uint")),
        "f" => Value::Float(f64::from_bits(
            u64::from_str_radix(body, 16).expect("float bits"),
        )),
        "s" => Value::Str(unhex_str(body)),
        "r" => Value::Rune(
            char::from_u32(body.parse::<i64>().expect("rune") as u32).expect("valid rune"),
        ),
        "y" => Value::Bytes(unhex(body)),
        "e" => Value::Error(unhex_str(body)),
        "l" => Value::Slice(parse_args(&unhex_str(body))),
        other => panic!("unknown argspec tag {other:?}"),
    }
}

#[test]
fn matches_go_fmt_byte_for_byte() {
    use std::collections::BTreeMap;

    // `GOFMT_GOLDEN` lets the randomized fuzz harness point this replay at a
    // freshly generated corpus.
    let override_path = std::env::var("GOFMT_GOLDEN");
    let path = override_path.clone().unwrap_or_else(|_| {
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/testdata/gofmt_golden.tsv"
        )
        .to_string()
    });
    let golden = std::fs::read_to_string(&path)
        .expect("golden file; regenerate with color-parity-oracle/gofmt_golden");

    let mut total = 0usize;
    let mut failed = 0usize;
    // Grouped by format string so that a systematic gap in one verb shows up as
    // a single entry instead of thousands of near-identical lines.
    let mut by_format: BTreeMap<String, (usize, String)> = BTreeMap::new();

    for (lineno, line) in golden.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        let mut fields = line.split('\t');
        let kind = fields.next().expect("kind");
        let format = unhex_str(fields.next().expect("format"));
        let argspec = fields.next().expect("argspec");
        // Compared as raw bytes: Go's output is a byte string.
        let want = unhex(fields.next().expect("result"));

        let args = parse_args(argspec);
        let got = match kind {
            "sprintf" => gofmt::sprintf(&format, &args),
            "sprint" => gofmt::sprint(&args),
            "sprintln" => gofmt::sprintln(&args),
            other => panic!("unknown kind {other:?}"),
        };

        total += 1;
        if got.as_bytes() != want.as_slice() {
            failed += 1;
            if let Ok(path) = std::env::var("PARITY_DUMP") {
                use std::io::Write as _;
                let mut f = std::fs::OpenOptions::new()
                    .create(true)
                    .append(true)
                    .open(&path)
                    .expect("dump file");
                writeln!(
                    f,
                    "{}\t{}\t{}\t{:?}\t{:?}",
                    kind,
                    format,
                    argspec,
                    String::from_utf8_lossy(&want),
                    got
                )
                .ok();
            }
            let key = format!("{kind} {format:?}");
            let entry = by_format.entry(key).or_insert_with(|| {
                (
                    0,
                    format!(
                        "line {}: args={}\n     want: {:?}\n      got: {:?}",
                        lineno + 1,
                        argspec,
                        String::from_utf8_lossy(&want),
                        got
                    ),
                )
            });
            entry.0 += 1;
        }
    }

    let mut report = String::new();
    if failed != 0 {
        let limit: usize = std::env::var("PARITY_REPORT_LIMIT")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(60);
        for (format, (count, example)) in by_format.iter().take(limit) {
            report.push_str(&format!("\n  {format}  ({count} cases)\n     {example}\n"));
        }
    }

    assert_eq!(
        failed,
        0,
        "{failed} of {total} Go fmt parity cases failed across {} distinct formats:\n{report}",
        by_format.len()
    );

    // A corpus that shrank is a corpus that stopped being evidence, so the
    // committed file is held to its exact record count and an injected one to a
    // floor. Either way the replay has to have compared something.
    match override_path {
        Ok(injected) => assert!(
            total > 0,
            "corpus {injected} replayed no cases; regenerate it with color-parity-oracle/fuzz_parity"
        ),
        Err(_) => assert_eq!(
            total, COMMITTED_CASES,
            "committed gofmt corpus holds {total} cases, expected {COMMITTED_CASES}; \
             regenerate it with color-parity-oracle/gofmt_golden"
        ),
    }

    eprintln!("verified {total} Go fmt parity cases against real Go output");
}
